package com.palmclaw.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

enum class UiLanguage {
    English,
    Chinese
}

val LocalUiLanguage = compositionLocalOf { UiLanguage.English }

private val chineseFallbackTranslations = mapOf(
    "Actions" to "操作",
    "Adapters" to "连接器",
    "Add one only when you need MCP." to "只有在需要 MCP 时再添加服务器。",
    "Add Server" to "添加服务器",
    "Add attachment" to "添加附件",
    "Advanced" to "高级",
    "After filling the fields, tap Save at the bottom to start the Discord connection." to "填完字段后，点击底部“保存”以启动 Discord 连接。",
    "After filling the fields, tap Save at the bottom to start the Slack connection." to "填完字段后，点击底部“保存”以启动 Slack 连接。",
    "After selecting a provider, tap here to open the official API key page." to "选择提供方后，可点击这里跳转到官方 API 密钥页面。",
    "After Save, send one message to the bot from Feishu." to "保存后，从飞书给机器人发送一条消息。",
    "Agent" to "智能体",
    "Agent Logs" to "智能体日志",
    "Allowed Chat ID" to "允许的聊天 ID",
    "Allowed Open IDs" to "允许的 Open ID",
    "Allowed" to "允许",
    "Allowed User IDs" to "允许的用户 ID",
    "Always-on" to "常驻",
    "Always-on Service" to "常驻服务",
    "API Key" to "API 密钥",
    "App token example" to "App Token 示例",
    "Ask anything" to "输入任何内容",
    "Audio" to "音频",
    "Auth Token" to "认证 Token",
    "Author" to "作者",
    "Auto reply" to "自动回复",
    "Back" to "返回",
    "Background service and reliability" to "后台服务与稳定性",
    "Background service and reliability." to "后台服务与稳定性。",
    "Base URL" to "基础 URL",
    "Endpoint URL" to "接口地址",
    "Battery" to "电池",
    "Battery optimization" to "电池优化",
    "Battery Settings" to "电池设置",
    "Beginning of chat" to "聊天开始处",
    "Best with charging and battery optimization off." to "建议在充电且关闭电池优化时使用。",
    "Bot token example" to "Bot Token 示例",
    "Bound" to "已绑定",
    "Cache Hit Rate" to "缓存命中率",
    "Cached Input" to "缓存输入",
    "Cancel" to "取消",
    "Channel" to "渠道",
    "Channel settings." to "渠道设置。",
    "Channels" to "渠道",
    "Channels & Configuration" to "渠道与配置",
    "Charging" to "充电中",
    "Chat" to "聊天",
    "Choose a section." to "选择一个分区。",
    "Choose how the agent refers to you, and what the agent should be called." to "设置智能体如何称呼你，以及智能体的名称。",
    "Choose how the bot should respond in this channel." to "选择机器人在此渠道中的回复方式。",
    "Choose how the bot should respond in this conversation." to "选择机器人在此会话中的回复方式。",
    "Choose the app language now. You can change it later in Settings." to "现在先选择应用语言，之后也可以在设置中修改。",
    "Clear" to "清空",
    "Close" to "关闭",
    "Collapse" to "收起",
    "Collapse advanced" to "收起高级选项",
    "Common setup" to "通用设置",
    "Complete a few basics before the first chat." to "在第一次聊天前先完成几个基础设置。",
    "Compatibility" to "兼容性",
    "Configure" to "配置",
    "Configure session channel" to "配置会话渠道",
    "Configured" to "已配置",
    "Confirm" to "确认",
    "Connect remote MCP servers." to "连接远程 MCP 服务器。",
    "Connect your provider endpoint and API key." to "连接你的提供方端点和 API 密钥。",
    "Connected" to "已连接",
    "Connecting" to "连接中",
    "Connection" to "连接",
    "Connection Diagnostics" to "连接诊断",
    "Connection mode" to "连接模式",
    "Consent required" to "需要授权",
    "Communication" to "通信",
    "Context Messages" to "上下文消息数",
    "Continue" to "继续",
    "Core features and how to use them." to "核心功能与使用方式。",
    "Core features and how to use them" to "核心功能与使用方式",
    "Create" to "创建",
    "Create a Feishu app in Feishu Open Platform, enable Bot capability, then copy App ID and App Secret." to "在飞书开放平台创建应用，启用 Bot 能力，然后复制 App ID 和 App Secret。",
    "Create a separate workspace for a task, person, or channel." to "为任务、联系人或渠道创建独立工作区。",
    "Create a Slack app from scratch, then enable Socket Mode." to "从零创建一个 Slack 应用，然后启用 Socket Mode。",
    "Create a WeCom AI Bot, choose API mode with long connection, then copy Bot ID and Secret." to "创建一个企业微信机器人，选择 API 长连接模式，然后复制机器人 ID 和密钥。",
    "Create Session" to "创建会话",
    "Create session" to "创建会话",
    "Cron Logs" to "Cron 日志",
    "Cron is for scheduled work such as reminders, checks, or session-based message dispatches." to "Cron 适合做定时任务，例如提醒、检查，或按会话触发的消息分发。",
    "Cron scheduler" to "Cron 调度",
    "Current Route" to "当前路由",
    "Current routing and status." to "当前路由与状态。",
    "Current totals for this provider." to "当前提供方的累计统计。",
    "Current totals for requests." to "当前请求累计统计。",
    "Current totals for requests" to "当前请求累计统计",
    "Default Tool Timeout (sec)" to "默认工具超时（秒）",
    "Delete" to "删除",
    "Delete Session" to "删除会话",
    "Delete session" to "删除会话",
    "Delete session '%s'? This cannot be undone." to "确定删除会话“%s”吗？此操作无法撤销。",
    "Detail" to "详情",
    "Detect Chats" to "检测会话",
    "Detect Senders" to "检测发件人",
    "Detecting..." to "检测中...",
    "Developer Portal" to "开发者平台",
    "Details" to "详情",
    "Disabled" to "已禁用",
    "Discord Bot Token" to "Discord Bot Token",
    "Downloads" to "下载量",
    "Edit Doc" to "编辑文档",
    "Edit HEARTBEAT.md" to "编辑 HEARTBEAT.md",
    "Email" to "邮箱",
    "Enable cron and set basic limits." to "启用 Cron 并设置基础限制。",
    "Enable cron and set basic limits" to "启用 Cron 并设置基础限制",
    "Enable Developer Mode in Discord. Right-click your avatar and Copy User ID if you want an allow list. Right-click the target channel and Copy Channel ID." to "在 Discord 中启用 Developer Mode。如果要使用允许列表，右键你的头像复制 User ID；右键目标频道复制 Channel ID。",
    "Enable MCP Remote" to "启用 MCP 远程",
    "Enabled" to "已启用",
    "Encrypt Key" to "加密密钥",
    "Endpoint and model" to "端点与模型",
    "Endpoint and model." to "端点与模型。",
    "Enter IMAP settings for receiving mail." to "填写用于收取邮件的 IMAP 设置。",
    "Enter SMTP settings for replies." to "填写用于回复邮件的 SMTP 设置。",
    "Enter the target conversation ID. Slack channel, group, and DM IDs usually start with C, G, or D." to "输入目标会话 ID。Slack 的频道、群组和私聊 ID 通常以 C、G 或 D 开头。",
    "Error" to "错误",
    "Exact alarm" to "精确闹钟",
    "Example: 123456789012345678" to "示例：123456789012345678",
    "Example: C123ABC45 or D123ABC45" to "示例：C123ABC45 或 D123ABC45",
    "Example: Research" to "示例：Research",
    "Expand advanced" to "展开高级选项",
    "Experimental" to "实验中",
    "Fallback limit when a tool has no own timeout." to "工具未单独设置超时时使用的兜底限制。",
    "Fallback limit when a tool has no own timeout" to "工具未单独设置超时时使用的兜底限制",
    "Feishu" to "飞书",
    "Feishu App ID" to "飞书 App ID",
    "Feishu App Secret" to "飞书 App Secret",
    "Files" to "文件",
    "Filled automatically after Detect Chats" to "执行“检测会话”后会自动填充",
    "For everyday use, start with the local session. Make sure your provider works first, then enable channels, cron, heartbeat, or MCP only when needed." to "日常使用建议先从本地会话开始。先确认提供方可用，再按需要开启渠道、Cron、Heartbeat 或 MCP。",
    "From Address" to "发件地址",
    "From the Telegram account you want to bind, send one message to the bot." to "用你要绑定的 Telegram 账号给机器人发送一条消息。",
    "Gateway" to "网关",
    "Gateway idle" to "网关空闲",
    "Gmail usually works with IMAP + SMTP app passwords." to "Gmail 通常可通过 IMAP + SMTP 应用专用密码使用。",
    "Good prompts usually include a goal, constraints, and the desired output format. The clearer the request, the more stable the result." to "好的提示通常包含目标、约束和期望输出格式。请求越清晰，结果通常越稳定。",
    "Guide" to "指南",
    "Heartbeat" to "心跳",
    "Heartbeat runs a prompt on a fixed interval, using content from HEARTBEAT.md. It is useful for routine checks, daily summaries, or self-driven reminders." to "Heartbeat 会按固定间隔运行一段提示词，内容来自 HEARTBEAT.md，适合做例行检查、日报总结或自驱提醒。",
    "Heartbeat works best for lightweight and repeatable jobs. More interactive or strict workflows are usually better handled through regular sessions or cron." to "Heartbeat 最适合轻量、可重复的任务；更强交互或更严格的流程，通常更适合放到普通会话或 Cron。",
    "Hidden" to "隐藏",
    "Hide" to "收起",
    "Hide Key" to "隐藏密钥",
    "Hide Logs" to "隐藏日志",
    "Hide Tokens" to "隐藏 Token",
    "How many tool-call loops one run may use." to "单次运行最多允许多少轮工具调用。",
    "How many tool-call loops one run may use" to "单次运行最多允许多少轮工具调用",
    "If a connection looks wrong, check Connection first and Configure second. Connection shows the current state, while Configure is where you change setup." to "如果连接看起来不对，先看 Connection，再看 Configure。前者展示当前状态，后者负责修改配置。",
    "If a job does not behave as expected, check whether the job itself is enabled, whether the schedule makes sense, and whether the target session or channel is available." to "如果某个任务行为异常，先看任务本身是否启用、调度是否合理，以及目标会话或渠道是否可用。",
    "If an MCP server looks unavailable, first check the URL, auth token, and tool timeout, then confirm the server itself is healthy." to "如果某个 MCP 服务器看起来不可用，先检查 URL、认证 Token 和工具超时，再确认服务端本身是否健康。",
    "If something matters only to one session, keep it in that session's history. Put information into shared memory only when it should be visible across sessions." to "如果某条信息只和一个会话相关，就留在该会话历史里；只有需要跨会话共享时，再写入共享记忆。",
    "If the result looks wrong, check the current session, provider setup, available tools, and recent messages before resetting everything." to "如果结果看起来不对，先检查当前会话、提供方配置、可用工具和最近消息，不要一上来就重置所有设置。",
    "If you are unsure what is available, check the tool descriptions or ask the agent to list the relevant options first." to "如果你不确定当前有哪些工具可用，先查看工具说明，或者让智能体先列出可选项。",
    "If you repeatedly do the same kind of work, such as structured summaries, API routines, or standard reviews, skills can make behavior much more consistent." to "如果你经常做同一类工作，比如结构化总结、固定 API 流程或标准审查，Skills 会让行为更稳定。",
    "If you work on different projects, people, or platforms, split them into separate sessions. This keeps context cleaner and reduces the chance of sending to the wrong place." to "如果你同时处理多个项目、多人沟通或多个平台，建议拆成独立会话。这样上下文更干净，也更不容易发错地方。",
    "Ignored" to "已忽略",
    "IMAP Host" to "IMAP 主机",
    "IMAP Password / App Password" to "IMAP 密码 / 应用专用密码",
    "IMAP Port" to "IMAP 端口",
    "IMAP Username" to "IMAP 用户名",
    "In Bot settings, enable MESSAGE CONTENT INTENT. If you plan to use an allow list, enable SERVER MEMBERS INTENT too." to "在 Bot 设置中启用 MESSAGE CONTENT INTENT。如果你要使用允许列表，也请启用 SERVER MEMBERS INTENT。",
    "Input" to "输入",
    "Install the app to your workspace, then copy the bot token." to "将应用安装到工作区，然后复制 bot token。",
    "Interval (sec)" to "间隔（秒）",
    "Interval and doc" to "间隔与文档",
    "Interval and doc." to "间隔与文档。",
    "Invalid sender" to "发送方无效",
    "Invalid target" to "目标无效",
    "Invite the bot to your server from OAuth2 URL Generator. Use scope bot and permissions Send Messages and Read Message History." to "在 OAuth2 URL Generator 中邀请机器人进入服务器。使用 bot scope，并授予 Send Messages 和 Read Message History 权限。",
    "Issues" to "异常",
    "It works best while charging, on a stable network, and with battery optimization disabled." to "它在充电、网络稳定且关闭电池优化时效果最好。",
    "Jobs" to "任务",
    "Jobs and limits" to "任务与限制",
    "Jobs and limits." to "任务与限制。",
    "Keep channels alive in background." to "让渠道在后台持续保持运行。",
    "Keep Screen Awake" to "保持屏幕常亮",
    "Language" to "语言",
    "Last Error" to "最近错误",
    "Last Status" to "上次状态",
    "Last subject" to "上一封主题",
    "License" to "许可证",
    "Limits and logs" to "限制与日志",
    "Limits and logs." to "限制与日志。",
    "LLM Call Timeout (sec)" to "LLM 调用超时（秒）",
    "Loading chat..." to "正在加载聊天...",
    "Loading cron jobs..." to "正在加载 Cron 任务...",
    "LOCAL" to "本地",
    "Local chat for administration." to "用于管理和诊断的本地聊天。",
    "Local only" to "仅本地",
    "Mailbox consent granted" to "邮箱授权已授予",
    "Max Jobs" to "最大任务数",
    "Max Tool Rounds" to "工具轮次上限",
    "Maximum tool output kept in chat context." to "保留在聊天上下文中的工具输出上限。",
    "Maximum tool output kept in chat context" to "保留在聊天上下文中的工具输出上限",
    "MCP connects external server-side capabilities so the agent can use remote tools." to "MCP 用来接入外部服务器侧能力，让智能体可以调用远程工具。",
    "MCP Remote" to "MCP 远程",
    "Memory" to "记忆",
    "Memory Consolidation Window" to "记忆整理窗口",
    "Memory has two layers: shared memory and session history. Shared memory is for long-term facts, while session history keeps the process and conclusions of a specific session." to "记忆分为两层：共享记忆和会话历史。共享记忆适合长期事实，会话历史则保留某个会话里的过程和结论。",
    "mention" to "仅 @ 时",
    "mention: reply only when @mentioned. open: reply to all messages in this channel." to "mention：仅在被 @ 时回复。open：回复该渠道中的所有消息。",
    "Message threshold before memory is compacted." to "触发记忆整理前的消息阈值。",
    "Message threshold before memory is compacted" to "触发记忆整理前的消息阈值",
    "Min Interval (ms)" to "最小间隔（毫秒）",
    "Missing app credentials" to "缺少应用凭证",
    "Missing bot credentials" to "缺少机器人凭证",
    "Missing bot/app token" to "缺少 Bot/App Token",
    "Missing channel id" to "缺少渠道 ID",
    "Missing mailbox credentials" to "缺少邮箱凭证",
    "Missing token" to "缺少 Token",
    "Model" to "模型",
    "Model, endpoint, and API key." to "模型、端点与 API 密钥。",
    "More settings below" to "更多设置如下",
    "Most users do not need skills on day one. Get sessions, tools, and channels working first, then add skills only when they clearly help." to "大多数用户第一天并不需要 Skills。先把会话、工具和渠道跑通，再在确实有帮助时加入 Skills。",
    "Names" to "名称",
    "Network" to "网络",
    "Next" to "下一步",
    "Next Run" to "下次运行",
    "No" to "否",
    "No agent logs yet." to "还没有智能体日志。",
    "No agent logs yet" to "还没有智能体日志",
    "No cron jobs yet." to "还没有 Cron 任务。",
    "No cron jobs yet" to "还没有 Cron 任务",
    "No cron logs yet." to "还没有 Cron 日志。",
    "No cron logs yet" to "还没有 Cron 日志",
    "No detected chats yet." to "还没有检测到会话。",
    "No detected senders yet." to "还没有检测到发件人。",
    "No MCP servers configured." to "还没有配置 MCP 服务器。",
    "No MCP servers configured" to "还没有配置 MCP 服务器",
    "No user-created sessions yet." to "还没有用户创建的会话。",
    "None" to "无",
    "Not connected" to "未连接",
    "Not configured" to "未配置",
    "Not selected" to "未选择",
    "Not set" to "未设置",
    "Notification" to "通知",
    "Off" to "关闭",
    "Offline" to "离线",
    "On" to "开启",
    "One ID per line or comma-separated" to "每行一个 ID，或用逗号分隔",
    "One open_id per line, or * to allow all" to "每行一个 open_id，或使用 * 允许全部",
    "One user ID per line, or * to allow all" to "每行一个用户 ID，或使用 * 允许全部",
    "Open" to "打开",
    "Open attachment" to "打开附件",
    "Open BotFather, send /newbot, then create a bot and copy its HTTP API token." to "打开 BotFather，发送 /newbot，创建机器人并复制其 HTTP API Token。",
    "Open channel settings" to "打开渠道设置",
    "Open media" to "打开媒体",
    "Open menu" to "打开菜单",
    "Open provider API key page" to "打开提供方 API 密钥页面",
    "Open Platform" to "开放平台",
    "Open the bot in WeCom and send one message so the app can detect the conversation." to "在企业微信中打开机器人并发送一条消息，让应用能检测到该会话。",
    "Open the Discord Developer Portal, create an application, then open Bot and add a bot." to "打开 Discord Developer Portal，创建应用，然后进入 Bot 页面添加机器人。",
    "Optional fields only." to "以下字段为可选项。",
    "Optional: add Allowed User IDs. If set, only those users can trigger replies. DMs still require the sender to be in the allow list." to "可选：填写 Allowed User IDs。设置后，只有这些用户可以触发回复。私聊同样要求发送方在允许列表中。",
    "Output" to "输出",
    "Overview" to "概览",
    "PalmClaw is a session-based local AI assistant. You can run the agent in different sessions, connect channels, schedule jobs, and keep important information in memory." to "PalmClaw 是一个按会话组织的本地 AI 助手。你可以在不同会话里运行智能体、连接渠道、安排任务，并把重要信息保存到记忆中。",
    "Paste the token, then tap Save at the bottom. This starts Telegram polling." to "粘贴 Token，然后点击底部“保存”，即可启动 Telegram 轮询。",
    "Pause" to "暂停",
    "Pending detection" to "等待检测",
    "Periodic prompt driven by HEARTBEAT.md." to "按固定间隔运行 HEARTBEAT.md 中定义的提示词。",
    "Periodic prompt driven by HEARTBEAT.md" to "按固定间隔运行 HEARTBEAT.md 中定义的提示词",
    "Preparing..." to "正在准备...",
    "Play" to "播放",
    "Prepare a mailbox for the bot. IMAP is used to read mail and SMTP is used to send replies." to "为机器人准备一个邮箱。IMAP 用于收信，SMTP 用于发送回复。",
    "Preview" to "预览",
    "Private: ou_xxx, Group: oc_xxx" to "私聊：ou_xxx，群组：oc_xxx",
    "Processing..." to "处理中...",
    "Provider" to "提供方",
    "Publish the app, then tap Save at the bottom to start the long connection." to "发布应用，然后点击底部“保存”以启动长连接。",
    "Ready" to "就绪",
    "Recent messages kept for each model turn." to "每轮模型调用保留的最近消息数。",
    "Recent messages kept for each model turn" to "每轮模型调用保留的最近消息数",
    "Refresh" to "刷新",
    "Refresh connection status" to "刷新连接状态",
    "Remote servers" to "远程服务器",
    "Remote servers." to "远程服务器。",
    "Remove" to "移除",
    "Remove attachment" to "移除附件",
    "Rename Session" to "重命名会话",
    "Rename session" to "重命名会话",
    "Requests" to "请求数",
    "Requirements" to "要求",
    "Response Mode" to "回复模式",
    "Response modes" to "回复模式",
    "Route" to "路由",
    "Run" to "运行",
    "Run it now or edit the heartbeat doc." to "立即运行，或编辑心跳文档。",
    "Run it now or edit the heartbeat doc" to "立即运行，或编辑心跳文档",
    "Running" to "运行中",
    "Runtime" to "运行",
    "Save" to "保存",
    "Saving..." to "保存中...",
    "Schedule" to "计划",
    "Scheduled jobs and recent state." to "计划任务与最近状态。",
    "Scheduler" to "调度器",
    "Scroll to latest" to "滚动到最新消息",
    "Search Provider" to "搜索提供方",
    "Select Channel" to "选择渠道",
    "Select a channel to configure binding for this session." to "选择一个渠道来为当前会话配置绑定。",
    "Select Long Connection mode, add event im.message.receive_v1, then grant the required messaging permissions." to "选择 Long Connection 模式，添加 im.message.receive_v1 事件，并授予所需消息权限。",
    "Send" to "发送",
    "Sender Email Address" to "发送方邮箱地址",
    "Server" to "服务器",
    "Server Name" to "服务器名称",
    "Servers" to "服务器",
    "Service" to "服务",
    "Session and route status." to "会话与路由状态。",
    "Session and route status" to "会话与路由状态",
    "Session Name" to "会话名称",
    "Session routes" to "会话路由",
    "Session routes." to "会话路由。",
    "Session Settings" to "会话设置",
    "Sessions" to "会话",
    "Settings" to "设置",
    "Show Key" to "显示密钥",
    "Show Logs" to "显示日志",
    "Show Tokens" to "显示 Token",
    "Skills" to "技能",
    "Skills extend the agent with extra workflows and knowledge. They are useful for packaging repeatable tasks, fixed procedures, or domain-specific guidance." to "Skills 会给智能体增加额外的工作流和知识，适合封装可重复任务、固定流程或领域化指引。",
    "Slack API" to "Slack API",
    "Slack App Token (xapp)" to "Slack App Token (xapp)",
    "Slack Bot Token (xoxb)" to "Slack Bot Token (xoxb)",
    "SMTP Host" to "SMTP 主机",
    "SMTP Password / App Password" to "SMTP 密码 / 应用专用密码",
    "SMTP Port" to "SMTP 端口",
    "SMTP Username" to "SMTP 用户名",
    "Source" to "来源",
    "Source URL" to "来源 URL",
    "Start Chat" to "开始聊天",
    "Starting" to "启动中",
    "State" to "状态",
    "Status" to "状态",
    "Step 2" to "第 2 步",
    "Step 3" to "第 3 步",
    "Stop" to "停止",
    "Stopped" to "已停止",
    "Summary" to "摘要",
    "Switch language" to "切换语言",
    "System" to "系统",
    "Tap Detect Chats, choose the conversation, then tap Save again to finish binding." to "点击“检测会话”，选择对话后，再次点击“保存”完成绑定。",
    "Tap Detect Chats, choose the detected conversation, then tap Save again." to "点击“检测会话”，选择检测到的会话后，再次点击“保存”。",
    "Tap Detect Chats, then choose the conversation to bind." to "点击“检测会话”，然后选择要绑定的会话。",
    "Tap Detect Senders, choose the sender address to bind, then tap Save again." to "点击“检测发件人”，选择要绑定的发件地址后，再次点击“保存”。",
    "Tap Save once to start mailbox polling, then send one email to this account." to "先点击一次“保存”启动邮箱轮询，然后向该邮箱发送一封邮件。",
    "Tap Save once to start the long connection." to "点击一次“保存”以启动长连接。",
    "Target" to "目标",
    "Target Channel ID" to "目标渠道 ID",
    "Target ID" to "目标 ID",
    "Test API" to "测试 API",
    "Testing..." to "测试中...",
    "The agent is the core worker. When you send a message, it uses the current session context, available tools, and memory to decide what to do next." to "智能体是核心执行者。你发送消息后，它会结合当前会话上下文、可用工具和记忆来决定下一步动作。",
    "The local session is good for admin, diagnostics, and control. Bound remote sessions are better for real conversations through Telegram, email, WeCom, and similar channels." to "本地会话适合做管理、诊断和控制；绑定远程渠道的会话更适合通过 Telegram、邮箱、企业微信等渠道进行真实对话。",
    "These names will be used in chat and stored in memory." to "这些名称会用于聊天，并写入记忆。",
    "This session stays local." to "这个会话仅保留在本地。",
    "Time limit for one model request." to "单次模型请求的时间上限。",
    "Time limit for one model request" to "单次模型请求的时间上限",
    "To validate behavior quickly, trigger it manually first and enable scheduling only after the output looks right." to "如果想快速验证效果，先手动触发一次，确认输出合适后再打开定时执行。",
    "Toggle theme" to "切换主题",
    "Token example" to "Token 示例",
    "Token Usage" to "Token 统计",
    "Tool" to "工具",
    "Tool Toggles" to "工具开关",
    "Tool Result Max Chars" to "工具结果最大字符数",
    "Tool Timeout (sec)" to "工具超时（秒）",
    "Tools" to "工具",
    "Message" to "消息",
    "Deliver a reply to the current chat target." to "向当前聊天目标发送回复。",
    "Session Send" to "会话发送",
    "Send a reply to a specific session." to "向指定会话发送回复。",
    "Session List" to "会话列表",
    "List available sessions." to "列出可用会话。",
    "Workspace" to "工作区",
    "Inspect the current workspace root and key directories." to "查看当前工作区根目录和关键目录。",
    "Subagent" to "子智能体",
    "Spawn a subagent for parallel work." to "启动子智能体并行处理任务。",
    "Session Status" to "会话状态",
    "Inspect current session channel routing." to "查看当前会话的渠道路由。",
    "Session Set" to "会话设置",
    "Update session-level channel routing." to "更新会话级渠道路由。",
    "Runtime Get" to "读取运行时",
    "Read runtime limits and timeout settings." to "读取运行时限制和超时设置。",
    "Runtime Set" to "设置运行时",
    "Update runtime limits and timeout settings." to "更新运行时限制和超时设置。",
    "Heartbeat Get" to "读取心跳",
    "Read heartbeat settings." to "读取心跳设置。",
    "Heartbeat Set" to "设置心跳",
    "Update heartbeat settings." to "更新心跳设置。",
    "Heartbeat Trigger" to "触发心跳",
    "Trigger heartbeat immediately." to "立即触发心跳。",
    "Cron" to "定时任务",
    "Manage scheduled jobs." to "管理计划任务。",
    "MCP Status" to "MCP 状态",
    "Inspect MCP server status and negotiated capabilities." to "查看 MCP 服务器状态和协商后的能力。",
    "MCP" to "MCP 工具",
    "Capabilities" to "能力",
    "Protocol" to "协议",
    "Web Search" to "网页搜索",
    "Search the web using the configured search provider." to "使用已配置的搜索提供方搜索网页。",
    "Web Fetch" to "网页抓取",
    "Fetch and extract a web page or remote document." to "获取并提取网页或远程文档内容。",
    "Summarize" to "总结",
    "Extract and summarize local or remote content." to "提取并总结本地或远程内容。",
    "Weather" to "天气",
    "Get current weather and forecast." to "获取当前天气和预报。",
    "Find" to "查找文件",
    "Inspect paths, list directories, and find entries by glob." to "检查路径、列出目录并按 glob 查找条目。",
    "Read" to "读取文件",
    "Read a supported local file." to "读取支持的本地文件。",
    "Write" to "写入文件",
    "Create, overwrite, or append a workspace text file." to "创建、覆盖或追加工作区文本文件。",
    "Edit" to "编辑文件",
    "Find and replace in a text file." to "在文本文件中查找并替换。",
    "Grep" to "文本搜索",
    "Search text inside files." to "在文件中搜索文本。",
    "Make Directory" to "创建目录",
    "Create a bounded workspace directory." to "在工作区边界内创建目录。",
    "Copy" to "复制",
    "Copy a bounded workspace file or directory." to "复制工作区边界内的文件或目录。",
    "Delete a bounded workspace file or directory." to "删除工作区边界内的文件或目录。",
    "Move" to "移动",
    "Move or rename a bounded workspace file or directory." to "移动或重命名工作区边界内的文件或目录。",
    "Memory Get" to "读取记忆",
    "Read long-term memory." to "读取长期记忆。",
    "Memory Set" to "设置记忆",
    "Update long-term memory." to "更新长期记忆。",
    "Memory History" to "记忆历史",
    "Read recent session history." to "读取最近会话历史。",
    "Memory Search" to "搜索记忆",
    "Search session history." to "搜索会话历史。",
    "Device Status" to "设备状态",
    "Inspect device status, permissions, and location." to "查看设备状态、权限和位置。",
    "Device" to "设备",
    "Run device actions such as opening settings or toggles." to "执行设备操作，例如打开设置或开关。",
    "Post, update, inspect, and cancel PalmClaw agent notifications." to
        "发布、更新、查看和取消 PalmClaw agent 通知。",
    "Media" to "媒体",
    "Record, capture, and open media workflows." to "录音、拍摄并打开媒体流程。",
    "Bluetooth" to "蓝牙",
    "Inspect Bluetooth and perform bounded BLE read and write tasks." to
        "查看蓝牙状态并执行有边界的 BLE 读取和写入任务。",
    "Calendar" to "日历",
    "Search and manage calendar events." to "搜索并管理日历事件。",
    "Contacts" to "联系人",
    "Search and manage contacts." to "搜索并管理联系人。",
    "Automation" to "自动化",
    "Personal" to "个人",
    "Web" to "网页",
    "Total" to "总计",
    "Trigger Now" to "立即触发",
    "Turn on Socket Mode, then create an app-level token with connections:write." to "开启 Socket Mode，然后创建带有 connections:write 权限的 app-level token。",
    "Unavailable" to "不可用",
    "Alarm" to "闹钟",
    "Unbound" to "未绑定",
    "Usable" to "可用",
    "Use Always-on when you want the phone to keep handling remote messages in background. For normal chat and tool use, regular mode is usually enough." to "如果你希望手机在后台持续处理远程消息，可以开启常驻模式。普通聊天和工具调用通常使用常规模式就足够。",
    "User Guide" to "用户指南",
    "User ID example" to "用户 ID 示例",
    "userId or detected chatId" to "userId 或检测到的 chatId",
    "Uses long connection. No public URL is required." to "使用长连接，不需要公网 URL。",
    "Uses WebSocket long connection. No webhook or public IP required." to "使用 WebSocket 长连接，不需要 webhook 或公网 IP。",
    "Usually same as chat ID" to "通常与聊天 ID 相同",
    "Verification Token" to "校验 Token",
    "Version" to "版本",
    "Video" to "视频",
    "Video unavailable" to "视频不可用",
    "Visible" to "可见",
    "Waiting for chat detection" to "等待会话检测",
    "Waiting for detection" to "等待检测",
    "Waiting for sender detection" to "等待发送方检测",
    "WeCom" to "企业微信",
    "WeCom Bot ID" to "企业微信机器人 ID",
    "WeCom Secret" to "企业微信密钥",
    "Welcome" to "欢迎",
    "PalmClaw is the private AI assistant on your phone: simple, safe, and ready anytime." to "PalmClaw 是你手机上的私人 AI 助手：简单、安全、随时可用。",
    "Choose your app language. You can change it later." to "选择应用界面语言，之后也可以再改。",
    "Connect the model provider used for chat and tools." to "连接聊天和工具要使用的模型提供方。",
    "Choose the names used in chat. You can update them later." to "设置聊天中使用的名字，之后也可以修改。",
    "What happens next" to "接下来会发生什么",
    "What is the agent's name?" to "智能体叫什么名字？",
    "What should the agent call you?" to "智能体应该怎么称呼你？",
    "When configuring it, first make sure the global scheduler is enabled, then verify each job's schedule, next run time, and latest status." to "配置时先确认全局调度器已经开启，再检查每个任务的计划、下次运行时间和最近状态。",
    "Yes" to "是",
    "You" to "你",
    "You can manage the session connections here." to "你可以在这里管理会话连接。",
    "Add bot scopes chat:write, reactions:write, app_mentions:read, then enable Event Subscriptions for message and app mention events." to "添加 bot scopes：chat:write、reactions:write、app_mentions:read，然后启用 Event Subscriptions，并添加 message 和 app mention 事件。",
    "After filling App ID and App Secret, tap Save once at the bottom so PalmClaw starts Long Connection." to "填完 App ID 和 App Secret 后，先点击底部“保存”一次，让 PalmClaw 启动长连接。",
    "BotFather" to "BotFather",
    "Choose how Feishu group chats should trigger the bot. Private chats always reply directly." to "选择飞书群聊应如何触发机器人。私聊始终直接回复。",
    "Choose how this Feishu binding should react to incoming messages." to "选择这个飞书绑定应如何响应入站消息。",
    "Delete session '%s'?" to "删除会话“%s”？",
    "Discord" to "Discord",
    "In Events & Callbacks, select Long Connection, then add im.message.receive_v1." to "在 Events & Callbacks 中选择 Long Connection，然后添加 im.message.receive_v1。",
    "In Permission Management, add im:message and im:message.p2p_msg:readonly. If you test with @ in a group, also add im:message.group_at_msg:readonly." to "在 Permission Management 中添加 im:message 和 im:message.p2p_msg:readonly。如果你是在群里用 @ 测试，也要添加 im:message.group_at_msg:readonly。",
    "Leave blank to allow anyone in the channel to trigger replies." to "留空则允许频道里的任何人触发回复。",
    "Leave blank to allow anyone in this conversation to trigger replies." to "留空则允许这个会话里的任何人触发回复。",
    "Manual sender override. Usually chosen from Detect Senders." to "手动覆盖发件人。通常从“检测发件人”中选择。",
    "Manual target override. Private chat uses ou_xxx, group uses oc_xxx." to "手动覆盖目标。私聊使用 ou_xxx，群聊使用 oc_xxx。",
    "Manual target override. Use a detected chatId or a specific userId." to "手动覆盖目标。使用检测到的 chatId 或指定的 userId。",
    "Manual target override. Usually filled automatically after Detect Chats." to "手动覆盖目标。通常会在“检测会话”后自动填充。",
    "Manual target override. Usually filled by Detect Chats." to "手动覆盖目标。通常由“检测会话”自动填充。",
    "Notice" to "提示",
    "Only fill this if your Feishu app has a verification token configured." to "只有在你的飞书应用配置了 verification token 时才需要填写。",
    "Only fill this if your Feishu app requires encrypted events." to "只有在你的飞书应用要求加密事件时才需要填写。",
    "Publish the app, open it in Feishu, and confirm Long Connection while PalmClaw is running." to "发布应用，在飞书中打开它，并在 PalmClaw 运行时确认 Long Connection。",
    "Restricts replies to one chat. Usually the same as Telegram Chat ID." to "将回复限制在一个聊天里，通常与 Telegram Chat ID 相同。",
    "Restricts which senders can trigger replies for this binding." to "限制哪些发送者可以触发这个绑定的回复。",
    "Restricts which users can trigger replies. Use * to allow all." to "限制哪些用户可以触发回复。使用 * 表示允许全部。",
    "Selected" to "已选择",
    "Send one message to the bot from Feishu." to "从飞书给机器人发送一条消息。",
    "In Feishu, send one message that @mentions the bot. Private chats and group chats both require @ to trigger replies." to "在飞书里发送一条带 @ 机器人的消息。私聊和群聊都必须通过 @ 才会触发回复。",
    "mention: text messages require @bot. file, image, audio, and media messages can still arrive directly. open: reply to all messages in this chat." to "mention：文本消息需要 @机器人；文件、图片、音频和媒体消息仍可直接到达。open：回复这个会话中的所有消息。",
    "If you keep mention mode, send one @mention text message once before using Detect Chats. File messages do not need @." to "如果保持 mention 模式，请先发送一条带 @ 的文本消息，再使用“检测会话”。文件消息不需要 @。",
    "Use mention to require @ for text messages, or open to accept all messages in the bound chat." to "mention 模式下文本消息需要 @；open 模式下会接受已绑定会话中的所有消息。",
    "Slack" to "Slack",
    "Tap Detect Chats, choose the conversation to bind, then tap Save again." to "点击“检测会话”，选择要绑定的会话，然后再次点击“保存”。",
    "Telegram" to "Telegram",
    "Telegram Bot Token" to "Telegram Bot Token",
    "Telegram Chat ID" to "Telegram Chat ID",
    "Turn this off if you only want detection and manual replies." to "如果你只想做检测和手动回复，可以把它关闭。",
    "In WeCom Admin, go to Security & Management > Management Tools, then create an AI Bot." to "到企业微信后台，在“安全与管理”的“管理工具”里创建智能机器人。",
    "Choose Manual Create, then choose API mode with long connection. Copy the Bot ID and Secret." to "选择“手动创建”，再选择 API 模式和长连接，然后复制 Bot ID 和 Secret。",
    "Fill WeCom Bot ID and Secret below, then tap Save once to start the long connection." to "在下方填写企业微信机器人 ID 和密钥，然后先点击一次“保存”以启动长连接。",
    "After Save, go to Available Permissions and grant the message permission for the bot." to "保存后，到“可使用权限”里为机器人授权消息权限。",
    "open" to "open",
    "someone@example.com" to "someone@example.com"
)

// Prefer the explicit Chinese text passed by the caller.
// If it is blank, fall back to the shared translation table.
// If neither exists, keep the English source text.
fun localizedText(english: String, chinese: String = "", useChinese: Boolean): String {
    if (!useChinese) return english
    val explicitChinese = chinese.trim()
    if (explicitChinese.isNotBlank()) return explicitChinese
    return chineseFallbackTranslations[english]?.trim()?.takeIf { it.isNotBlank() } ?: english
}

@Composable
fun tr(english: String, chinese: String): String {
    return localizedText(
        english = english,
        chinese = chinese,
        useChinese = LocalUiLanguage.current == UiLanguage.Chinese
    )
}
