package com.palmclaw.ui

import com.palmclaw.config.AppSession
import com.palmclaw.providers.ProviderCatalog
import com.palmclaw.providers.ProviderProtocol
import com.palmclaw.config.AppLimits
import com.palmclaw.config.SearchProviderId
import com.palmclaw.ui.domain.AlwaysOnUiStatus
import com.palmclaw.ui.settings.UiBuiltInToolConfig
import com.palmclaw.ui.settings.UiClawHubSkillCard
import com.palmclaw.ui.settings.UiClawHubSkillDetail
import com.palmclaw.ui.settings.UiSkillConfig
import com.palmclaw.ui.settings.UiSkillDownloadStatus
import com.palmclaw.ui.settings.UiStagedSkillReview

/**
 * Single immutable view state consumed by the main chat UI.
 */
data class ChatUiState(
    val messages: List<UiMessage> = emptyList(),
    val messagesLoading: Boolean = false,
    val messagesLoadingOlder: Boolean = false,
    val canLoadOlderMessages: Boolean = false,
    val input: String = "",
    val composerAttachments: List<UiComposerAttachmentDraft> = emptyList(),
    val composerImporting: Boolean = false,
    val composerAttachmentError: String? = null,
    val isGenerating: Boolean = false,
    val onboardingCompleted: Boolean = false,
    val userDisplayName: String = "",
    val agentDisplayName: String = "PalmClaw",
    val onboardingUserDisplayName: String = "",
    val onboardingAgentDisplayName: String = "PalmClaw",
    val sessions: List<UiSessionSummary> = listOf(
        UiSessionSummary(
            id = AppSession.LOCAL_SESSION_ID,
            title = AppSession.LOCAL_SESSION_TITLE,
            isLocal = true
        )
    ),
    val currentSessionId: String = AppSession.LOCAL_SESSION_ID,
    val currentSessionTitle: String = AppSession.LOCAL_SESSION_TITLE,
    val settingsProviderConfigs: List<UiProviderConfig> = emptyList(),
    val settingsEditingProviderConfigId: String = "",
    val settingsProvider: String = AppLimits.DEFAULT_PROVIDER,
    val settingsProviderCustomName: String = "",
    val settingsProviderProtocol: ProviderProtocol = ProviderCatalog.defaultProtocol(AppLimits.DEFAULT_PROVIDER),
    val settingsBaseUrl: String = ProviderCatalog.defaultBaseUrl(
        AppLimits.DEFAULT_PROVIDER,
        ProviderCatalog.defaultProtocol(AppLimits.DEFAULT_PROVIDER)
    ),
    val settingsModel: String = ProviderCatalog.defaultModel(
        AppLimits.DEFAULT_PROVIDER,
        ProviderCatalog.defaultProtocol(AppLimits.DEFAULT_PROVIDER)
    ),
    val settingsApiKey: String = "",
    val settingsMaxToolRounds: String = AppLimits.DEFAULT_MAX_TOOL_ROUNDS.toString(),
    val settingsToolResultMaxChars: String = AppLimits.DEFAULT_TOOL_RESULT_MAX_CHARS.toString(),
    val settingsMemoryConsolidationWindow: String = AppLimits.DEFAULT_MEMORY_CONSOLIDATION_WINDOW.toString(),
    val settingsLlmCallTimeoutSeconds: String = AppLimits.DEFAULT_LLM_CALL_TIMEOUT_SECONDS.toString(),
    val settingsLlmConnectTimeoutSeconds: String = AppLimits.DEFAULT_LLM_CONNECT_TIMEOUT_SECONDS.toString(),
    val settingsLlmReadTimeoutSeconds: String = AppLimits.DEFAULT_LLM_READ_TIMEOUT_SECONDS.toString(),
    val settingsDefaultToolTimeoutSeconds: String = AppLimits.DEFAULT_TOOL_TIMEOUT_SECONDS.toString(),
    val settingsContextMessages: String = AppLimits.DEFAULT_CONTEXT_MESSAGES.toString(),
    val settingsToolArgsPreviewMaxChars: String = AppLimits.DEFAULT_TOOL_ARGS_PREVIEW_MAX_CHARS.toString(),
    val settingsBuiltInTools: List<UiBuiltInToolConfig> = emptyList(),
    val settingsInstalledSkills: List<UiSkillConfig> = emptyList(),
    val settingsSelectedSkillName: String = "",
    val settingsSelectedSkillDetail: UiSkillConfig? = null,
    val settingsClawHubStaffPicks: List<UiClawHubSkillCard> = emptyList(),
    val settingsClawHubPopular: List<UiClawHubSkillCard> = emptyList(),
    val settingsClawHubSearchQuery: String = "",
    val settingsClawHubSearchedQuery: String = "",
    val settingsClawHubSearchResults: List<UiClawHubSkillCard> = emptyList(),
    val settingsSelectedClawHubDetail: UiClawHubSkillDetail? = null,
    val settingsStagedSkillReview: UiStagedSkillReview? = null,
    val settingsSkillDownloadStatus: UiSkillDownloadStatus? = null,
    val settingsSkillsLoading: Boolean = false,
    val settingsClawHubLoading: Boolean = false,
    val settingsSkillActionInFlight: Boolean = false,
    val settingsSearchProvider: SearchProviderId = SearchProviderId.DuckDuckGo,
    val settingsSearchBraveApiKey: String = "",
    val settingsSearchTavilyApiKey: String = "",
    val settingsSearchJinaApiKey: String = "",
    val settingsSearchKagiApiKey: String = "",
    val settingsTokenInput: Long = 0L,
    val settingsTokenOutput: Long = 0L,
    val settingsTokenTotal: Long = 0L,
    val settingsTokenCachedInput: Long = 0L,
    val settingsTokenRequests: Long = 0L,
    val settingsCronEnabled: Boolean = false,
    val settingsCronMinEveryMs: String = AppLimits.DEFAULT_CRON_MIN_EVERY_MS.toString(),
    val settingsCronMaxJobs: String = AppLimits.DEFAULT_CRON_MAX_JOBS.toString(),
    val settingsCronJobs: List<UiCronJob> = emptyList(),
    val settingsCronJobsLoading: Boolean = false,
    val settingsCronLogs: String = "",
    val settingsAgentLogs: String = "",
    val settingsHeartbeatEnabled: Boolean = false,
    val settingsHeartbeatIntervalSeconds: String = AppLimits.DEFAULT_HEARTBEAT_INTERVAL_SECONDS.toString(),
    val settingsGatewayEnabled: Boolean = false,
    val settingsUseChinese: Boolean = false,
    val settingsDarkTheme: Boolean = false,
    val alwaysOnEnabled: Boolean = false,
    val alwaysOnKeepScreenAwake: Boolean = false,
    val alwaysOnCharging: Boolean = false,
    val alwaysOnBatteryOptimizationIgnored: Boolean = false,
    val alwaysOnRuntimeStatus: AlwaysOnUiStatus = AlwaysOnUiStatus(),
    val settingsTelegramBotToken: String = "",
    val settingsTelegramAllowedChatId: String = "",
    val settingsDiscordWebhookUrl: String = "",
    val settingsConnectedChannels: List<UiConnectedChannelSummary> = emptyList(),
    val settingsDiscordGatewayStatus: String = "",
    val settingsSlackGatewayStatus: String = "",
    val settingsFeishuGatewayStatus: String = "",
    val settingsEmailGatewayStatus: String = "",
    val settingsWeComGatewayStatus: String = "",
    val settingsMcpEnabled: Boolean = false,
    val settingsMcpServerName: String = AppLimits.DEFAULT_MCP_HTTP_SERVER_NAME,
    val settingsMcpServerUrl: String = "",
    val settingsMcpAuthToken: String = "",
    val settingsMcpToolTimeoutSeconds: String = AppLimits.DEFAULT_MCP_HTTP_TOOL_TIMEOUT_SECONDS.toString(),
    val settingsMcpServers: List<UiMcpServerConfig> = emptyList(),
    val settingsMcpRuntimeSnapshot: UiMcpRuntimeSnapshot = UiMcpRuntimeSnapshot(),
    val settingsMcpHasUnsavedChanges: Boolean = false,
    val settingsHeartbeatDoc: String = "",
    val settingsProviderTesting: Boolean = false,
    val settingsUpdateChecking: Boolean = false,
    val settingsUpdateAvailable: Boolean = false,
    val settingsUpdatePromptVisible: Boolean = false,
    val settingsUpdateNoticeVisible: Boolean = false,
    val settingsUpdateNoticeTitle: String = "",
    val settingsUpdateNoticeMessage: String = "",
    val settingsUpdateNoticeActionLabel: String = "",
    val settingsUpdateNoticeActionUrl: String = "",
    val settingsCurrentVersion: String = "",
    val settingsLatestVersion: String = "",
    val settingsUpdateReleaseUrl: String = "",
    val settingsUpdateDownloadUrl: String = "",
    val sessionBindingTelegramDiscovering: Boolean = false,
    val sessionBindingTelegramDiscoveryAttempted: Boolean = false,
    val sessionBindingTelegramCandidates: List<UiTelegramChatCandidate> = emptyList(),
    val sessionBindingTelegramInfo: String? = null,
    val sessionBindingFeishuDiscovering: Boolean = false,
    val sessionBindingFeishuDiscoveryAttempted: Boolean = false,
    val sessionBindingFeishuCandidates: List<UiFeishuChatCandidate> = emptyList(),
    val sessionBindingFeishuInfo: String? = null,
    val sessionBindingEmailDiscovering: Boolean = false,
    val sessionBindingEmailDiscoveryAttempted: Boolean = false,
    val sessionBindingEmailCandidates: List<UiEmailSenderCandidate> = emptyList(),
    val sessionBindingEmailInfo: String? = null,
    val sessionBindingWeComDiscovering: Boolean = false,
    val sessionBindingWeComDiscoveryAttempted: Boolean = false,
    val sessionBindingWeComCandidates: List<UiWeComChatCandidate> = emptyList(),
    val sessionBindingWeComInfo: String? = null,
    val settingsSaving: Boolean = false,
    val settingsInfo: String? = null
)
